- hosts: kubemaster
  tasks:
   - name: delete deployment in cluster
     shell: kubectl delete deployment 
   - name: delete namespace 
     shell: kubectl create ns webapp
   - name: stop kubernet cluster
     shell: kubectl 
   - name: remove container
     shell: docker container rm mydockercontainer
   - name: remove docker image
     shell: docker image rmi mondab2/docker-webapp
   - name: create new container
     shell: docker container run -itd --name mydockercontainer -p 9000:80 mondab2/docker-webapp
