- hosts: kubemaster
  tasks:
   - name: delete deployment in namespace
     shell: kubectl delete deployment webserver -n webserver-ns
   - name: delete services in namespace
     shell: kubectl delete service webserver -n webserver-ns
   - name: delete namespace
     shell: kubectl delete namespace webserver-ns 
   - name: create new namesapce webserver
     shell: kubectl create ns webserver-ns
   - name: create new deployment in webserver namespace
     shell: kubectl create -f deployment.yml -n webserver-ns

