apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver
    spec:
      containers:
      - image: mondab2/deploy-kub-clu-webpage
        name: webserver
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: LoadBlancer
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31200
  selector:
    app: webserver
